version: '3.8'
services:
  icbged-app:
    image: icbged
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-ff62e13-benarbia-f7b5.a.aivencloud.com:27703/defaultdb?sslMode=REQUIRED&user=avnadmin&password=AVNS_TN3z3VQwSsAYqL1my_o
      - SPRING_LIQUIBASE_URL=jdbc:mysql://mysql-ff62e13-benarbia-f7b5.a.aivencloud.com:27703/defaultdb?sslMode=REQUIRED&user=avnadmin&password=AVNS_TN3z3VQwSsAYqL1my_o
      - JHIPSTER_SLEEP=30
    ports:
      - 127.0.0.1:8080:8080

  icbged-mysql:
    image: mysql:8.0.28
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=icbged
    ports:
      - 127.0.0.1:3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
